import { PencilIcon, } from '@heroicons/react/outline';
import { useFormik } from 'formik';
import { useMutation, useQuery } from 'react-query';
import { useEffect } from 'react';

import { Button } from '@/components/Elements';
import { FormDrawer, Field } from '@/components/Form';
import { Authorization, ROLES } from '@/lib/authorization';
import { useNotificationStore } from '@/stores/notifications';
import { updateVersionSchema } from '@/utils/yup';
import { updateVersion } from './api';
import { useLanguageStore } from '@/stores/languages';
import { fetchLanguages } from '@/lib/api';
import { LanguageSelector } from '@/components/Language/LanguageSelector';
import { TranslatableInput } from '@/components/Form/TranslatableInput';
import { useTranslations } from '@/hooks/useTranslations';
import { TranslatableTextarea } from '@/components/Form/TranslatableTextarea';

interface FormikState {
  androidVersion: string;
  iosVersion: string;
  androidForceUpdate: boolean;
  iosForceUpdate: boolean;
  update_title: string;
  update_titleTranslations: Record<string, string>; // This will be generated by the hook
  update_message: string;
  update_messageTranslations: Record<string, string>; // This will be generated by the hook
  androidShowPopUp: boolean;
  iosShowPopUp: boolean;
}

export const UpdateVersion = ({ screenData }) => {
  const { addNotification } = useNotificationStore();
  const { data: fetchedLanguages = [] } = useQuery('languages', fetchLanguages);
  const setLanguages = useLanguageStore((state) => state.setLanguages);
  useEffect(() => {
    if (fetchedLanguages.length > 0) {
      setLanguages(fetchedLanguages);
    }
  }, [fetchedLanguages, setLanguages]);

  const {
    selectedLanguages,
    handleLanguageToggle,
    getFilteredTranslations,
    resetLanguages,
    setSelectedLanguages,
  } = useTranslations({
    translationFields: ['update_title', 'update_message'],
  });

  useEffect(() => {
    const validKeys = useLanguageStore.getState().languages.map(l => l.key);
    const langs = Object.values(screenData || {})
      .flatMap(o => (o && typeof o === 'object' ? Object.keys(o) : []))
      .filter(k => validKeys.includes(k));

    setSelectedLanguages([...new Set(langs)]);
  }, [screenData, setSelectedLanguages]);

  const initialValues: FormikState = {
    androidVersion: screenData?.android?.version || '1.0.0',
    iosVersion: screenData?.ios?.version || '1.0.0',
    androidForceUpdate: screenData?.android?.forceUpdate || false,
    iosForceUpdate: screenData?.ios?.forceUpdate || false,
    androidShowPopUp: screenData?.android?.showPopUp || false,
    iosShowPopUp: screenData?.ios?.showPopUp || false,
    update_title: screenData?.update_title || '',
    update_titleTranslations: screenData?.update_titleTranslations || {},
    update_message: screenData?.update_message || '',
    update_messageTranslations: screenData?.update_messageTranslations || {},
  };

  const formik = useFormik({
    initialValues,
    validationSchema: updateVersionSchema,
    onSubmit: (v) => onSubmit(v)
  });

  const { mutate, isLoading, isSuccess } = useMutation(updateVersion, {
    onSuccess: (message: string) => {
      
      resetLanguages();
      addNotification({
        type: 'success',
        title: message
      });
    }
  });

  const onSubmit = (state: FormikState) => {
    const translations = getFilteredTranslations(state,true);
    
    const { androidVersion, iosVersion, androidShowPopUp,
      iosShowPopUp, androidForceUpdate, iosForceUpdate, update_title, update_message } = state;
    
    mutate({
      android: { version: androidVersion, forceUpdate: androidForceUpdate, showPopUp: androidShowPopUp },
      ios: { version: iosVersion, forceUpdate: iosForceUpdate, showPopUp: iosShowPopUp },
      update_title: update_title,
      update_titleTranslations: translations?.update_titleTranslations || {},
      update_message: update_message,
      update_messageTranslations: translations?.update_messageTranslations || {},
    });
  };

  return (
    <Authorization allowedRoles={[ROLES.ADMIN]}>
      <FormDrawer
        isDone={isSuccess}
        triggerButton={
          <Button size="sm" variant="danger" startIcon={<PencilIcon className="h-4 w-4" />}>
            &nbsp;Update Version
          </Button>
        }
        title="Update Version Details"
        submitButton={
          <Button form="update-version" variant="danger" type="submit" size="sm" isLoading={isLoading}>
            Submit
          </Button>
        }
      >
        <LanguageSelector
          selectedLanguages={selectedLanguages}
          onToggle={handleLanguageToggle}
        />
        <form id="update-version" onSubmit={formik.handleSubmit} className="space-y-6">
          {/* General Update Info */}
          <div className="space-y-4">
            <TranslatableInput 
              label="Update Title" 
              formik={formik} 
              name="update_title" 
              translationField="update_titleTranslations" 
              selectedLanguages={selectedLanguages} 
            />
            <TranslatableTextarea 
              label="Update Message" 
              formik={formik} 
              name="update_message"
              translationField="update_messageTranslations"
              selectedLanguages={selectedLanguages}
            />
          </div>

          <div className="bg-gray-50 rounded-lg p-4">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-xl font-semibold text-gray-900 flex items-center">
                <div className="w-8 h-8 bg-green-100 rounded-lg flex items-center justify-center mr-3">
                  <svg className="w-5 h-5 text-green-600" fill="currentColor" viewBox="0 0 20 20">
                    <path d="M10 2a8 8 0 100 16 8 8 0 000-16zM8 12a2 2 0 114 0 2 2 0 01-4 0z" />
                  </svg>
                </div>
                Android
              </h3>
              <div className="flex items-center space-x-2">
                <span className="text-sm font-medium text-gray-700">Show Popup</span>
                <button
                  type="button"
                  onClick={() => formik.setFieldValue('androidShowPopUp', !formik.values.androidShowPopUp)}
                  className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 ${formik.values.androidShowPopUp ? 'bg-red-600' : 'bg-gray-200'
                    }`}
                >
                  <span
                    className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${formik.values.androidShowPopUp ? 'translate-x-6' : 'translate-x-1'
                      }`}
                  />
                </button>
              </div>
            </div>
            <div className={`grid grid-cols-1 md:grid-cols-2 gap-4 transition-opacity ${!formik.values.androidShowPopUp ? 'opacity-50 pointer-events-none' : ''}`}>
              <Field label="Version" formik={formik} name="androidVersion" disabled={!formik.values.androidShowPopUp} />
              <div className="flex items-center justify-between">
                <label htmlFor="androidForceUpdate" className="text-base font-medium text-gray-700">
                  Force Update Required
                </label>
                <button
                  type="button"
                  disabled={!formik.values.androidShowPopUp}
                  onClick={() => formik.setFieldValue('androidForceUpdate', !formik.values.androidForceUpdate)}
                  className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 ${formik.values.androidForceUpdate ? 'bg-red-600' : 'bg-gray-200'
                    }`}
                >
                  <span
                    className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${formik.values.androidForceUpdate ? 'translate-x-6' : 'translate-x-1'
                      }`}
                  />
                </button>
              </div>
            </div>
          </div>

          {/* iOS Version Section */}
          <div className="bg-gray-50 rounded-lg p-4">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-xl font-semibold text-gray-900 flex items-center">
                <div className="w-8 h-8 bg-blue-100 rounded-lg flex items-center justify-center mr-3">
                  <svg className="w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                    <path d="M10 2a8 8 0 100 16 8 8 0 000-16zM8 12a2 2 0 114 0 2 2 0 01-4 0z" />
                  </svg>
                </div>
                iOS
              </h3>
              <div className="flex items-center space-x-2">
                <span className="text-sm font-medium text-gray-700">Show Popup</span>
                <button
                  type="button"
                  onClick={() => formik.setFieldValue('iosShowPopUp', !formik.values.iosShowPopUp)}
                  className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 ${formik.values.iosShowPopUp ? 'bg-red-600' : 'bg-gray-200'
                    }`}
                >
                  <span
                    className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${formik.values.iosShowPopUp ? 'translate-x-6' : 'translate-x-1'
                      }`}
                  />
                </button>
              </div>
            </div>
            <div className={`grid grid-cols-1 md:grid-cols-2 gap-4 transition-opacity ${!formik.values.iosShowPopUp ? 'opacity-50 pointer-events-none' : ''}`}>
              <Field label="Version" formik={formik} name="iosVersion" disabled={!formik.values.iosShowPopUp} />
              <div className="flex items-center justify-between">
                <label htmlFor="iosForceUpdate" className="text-base font-medium text-gray-700">
                  Force Update Required
                </label>
                <button
                  type="button"
                  disabled={!formik.values.iosShowPopUp}
                  onClick={() => formik.setFieldValue('iosForceUpdate', !formik.values.iosForceUpdate)}
                  className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 ${formik.values.iosForceUpdate ? 'bg-red-600' : 'bg-gray-200'
                    }`}
                >
                  <span
                    className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${formik.values.iosForceUpdate ? 'translate-x-6' : 'translate-x-1'
                      }`}
                  />
                </button>
              </div>
            </div>
          </div>
        </form>
      </FormDrawer>
    </Authorization>
  );
};